<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Destinos2025Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('secciones')->insert([
            [
            'introduccion' => 'Inspírate para tu próxima aventura en cualquier rincón del planeta.',
            'parrafo' => 'Descubre el mundo a través de destinos que inspiran, sorprenden y despiertan el deseo de explorar. En esta sección encontrarás una cuidada selección de países que ofrecen experiencias únicas, desde paisajes naturales asombrosos hasta culturas milenarias, ciudades vibrantes y rincones poco explorados. Ya sea que sueñes con caminar entre templos antiguos en Asia, perderte en mercados coloridos de África, recorrer carreteras escénicas en Oceanía o descansar en playas paradisíacas del Caribe, aquí te damos opciones para todos los estilos de viaje y todos los tipos de viajeros. Cada país que te presentamos es una puerta abierta a nuevas aventuras, sabores, sonidos e historias. Explora el mapa, encuentra tu próximo destino y empieza a planear un viaje que quedará grabado en tu memoria para siempre. El mundo está lleno de maravillas… y todas te están esperando.',
            ],
            [
            'introduccion' => 'Lugares donde cada calle cuenta una historia y cada rincón tiene alma.',
            'parrafo' => 'Estos destinos cautivan por su personalidad única, su historia viva y su belleza atemporal. Aquí no se trata de grandes metrópolis, sino de urbes que enamoran por su arquitectura, su ambiente local y su capacidad de hacerte sentir como en casa. Desde callejuelas empedradas llenas de arte hasta plazas animadas donde la vida fluye lentamente, cada ciudad seleccionada en esta sección ofrece una experiencia íntima y auténtica. Son lugares ideales para caminar sin prisa, descubrir cafés escondidos, conversar con los locales y dejarse llevar por el ritmo propio de cada cultura. Ya sea un pueblo colonial en América Latina, una capital europea con siglos de historia, o una ciudad asiática que mezcla tradición y modernidad, aquí encontrarás destinos que no solo se visitan: se viven y se sienten. Perfectos para quienes valoran lo auténtico, lo estético y lo humano.',
            ],
            [
            'introduccion' => 'Explora paisajes que despiertan el alma y aventuras que te conectan con lo esencial.',
            'parrafo' => 'Si eres un espíritu inquieto que busca salir de la rutina y sumergirse en lo salvaje, lo puro y lo inesperado, aquí encontrarás destinos que te invitan a desafiar tus límites y reconectar con la Tierra: desde montañas majestuosas que te retan a escalar hasta selvas tropicales llenas de vida, lagos cristalinos, volcanes activos, glaciares imponentes y playas vírgenes donde el tiempo parece detenerse. Cada lugar está pensado para ofrecer experiencias intensas, ya sea a pie, en kayak, en bicicleta o simplemente contemplando el paisaje. Además de la aventura física, estos destinos te acercan a culturas que han vivido en armonía con la naturaleza por generaciones. Si buscas viajar con propósito, respirar aire puro, sentir la adrenalina y llevarte recuerdos que no caben en una foto, este es tu lugar.',
            ],
            /*[
            'titulo' => 'Machu Picchu, Perú',
            'descripcion' => 'Viajar a Machu Picchu es emprender un recorrido hacia el corazón de la civilización inca, una aventura que combina historia milenaria, esfuerzo físico, paisajes imponentes y una atmósfera mística difícil de igualar. Situada a más de 2,400 metros sobre el nivel del mar, esta ciudadela fue construida en lo alto de la selva montañosa, entre picos verdes y nubes que parecen acariciar las piedras. Declarada Patrimonio de la Humanidad por la UNESCO y una de las Nuevas Siete Maravillas del Mundo, su misterio sigue vivo: no se sabe con certeza cuál fue su función, pero sus templos, terrazas y canales demuestran un conocimiento asombroso de ingeniería y astronomía. El verdadero viaje comienza antes de llegar. Muchos aventureros eligen hacerlo a pie por el Camino Inca, una ruta ancestral de varios días que atraviesa paisajes andinos, bosques nubosos y otras ruinas escondidas. También existen rutas alternativas como el Salkantay Trek, más exigente, o el Inca Jungle Trek, que combina ciclismo de montaña, caminatas y rafting. Durante la travesía, el idioma español se mezcla con el quechua, la lengua indígena que aún se habla en muchas comunidades rurales. Aquí, la conexión con la Pachamama —la madre tierra— no es solo simbólica, sino parte viva del día a día. El clima puede ser cambiante, los caminos empinados, y las alturas un reto, pero cada paso hacia Machu Picchu es parte de un proceso transformador. Este no es solo un destino para ver; es uno para sentir y superar. En Machu Picchu no solo te asombras de lo que los incas fueron capaces de construir, sino también de lo que tú eres capaz de lograr para llegar allí.',
            'imagen' => 'peru.jpg',
            ],
            [
            'titulo' => 'Punta Cana, República Dominicana',
            'descripcion' => 'Punta Cana es, para muchos, sinónimo de resort, relax y playa; pero para los viajeros con espíritu aventurero, es mucho más que eso. Es la puerta de entrada a una región repleta de exploraciones culturales, paisajes salvajes y actividades que van desde lo acuático hasta lo selvático. Ubicada en la costa este de la República Dominicana, donde el mar Caribe se encuentra con el Atlántico, ofrece no solo belleza natural, sino también una inmersión en la identidad dominicana más profunda. Más allá de sus hoteles, puedes descubrir cuevas subterráneas como las del Parque Scape, navegar en catamarán hasta islas solitarias como Saona o Catalina, hacer tirolesas sobre la jungla, explorar manglares en kayak o recorrer senderos entre campos de caña de azúcar en buggies todo terreno. Cada una de estas actividades abre una ventana al lado menos conocido del país. El idioma predominante es el español, y en los pueblos cercanos aún se conserva una vida rural auténtica, con mercados locales, música en cada esquina y una gastronomía riquísima basada en mariscos frescos, plátanos y coco. La música —bachata, merengue, dembow— forma parte esencial del entorno y contagia alegría a cada paso. Punta Cana es perfecta para quienes buscan un equilibrio entre comodidad y aventura. Puedes tener una tarde de adrenalina y una noche de descanso frente al mar, o elegir vivir cada día como una nueva excursión. Lo importante es saber que detrás de las palmeras perfectas, hay todo un país por descubrir.',
            'imagen' => 'punta_cana.jpg',
            ],
            [
            'titulo' => 'Indonesia',
            'descripcion' => 'Indonesia es un archipiélago de contrastes infinitos, una nación compuesta por más de 17,000 islas donde cada rincón es una nueva oportunidad para la aventura, el asombro y la conexión con culturas milenarias. Desde los templos ancestrales de Java hasta las playas volcánicas de Sumatra, pasando por los volcanes activos de Flores y los arrecifes cristalinos de Raja Ampat, Indonesia es una tierra tan vasta como diversa, ideal para quienes buscan perderse —y encontrarse— en lo desconocido. El idioma oficial es el bahasa indonesia, pero en cada isla se hablan decenas de lenguas locales, reflejo de su enorme riqueza étnica y cultural. En Bali, la isla de los dioses, podrás surfear olas legendarias al amanecer y por la tarde participar en una ceremonia hindú junto a los lugareños. En Borneo, puedes adentrarte en la selva en busca de orangutanes, mientras que en Java puedes ascender al cráter humeante del volcán Bromo o al azul sobrenatural del Kawah Ijen, donde las llamas arden con fuego azul por la combustión del azufre. Las opciones para el viajero aventurero son prácticamente infinitas: senderismo, buceo de clase mundial, exploración de islas remotas, espeleología, inmersión cultural y retiros espirituales en medio de arrozales. Las comidas, preparadas con especias locales y una mezcla de influencias hindúes, chinas y musulmanas, son también una parte importante del viaje. Indonesia no es un destino para recorrer con prisa. Sus distancias, diversidad cultural y geografía desafiante exigen tiempo y disposición para el asombro. Es un país donde cada isla puede sentirse como un universo diferente, y donde cada aventura deja una huella profunda en el alma del viajero.',
            'imagen' => 'indonesia.jpg',
            ],
            [
            'titulo' => 'Kutaisi, Georgia',
            'descripcion' => 'Kutaisi es una ciudad histórica situada en el oeste de Georgia, considerada una de las más antiguas de Europa. Antiguamente capital del legendario reino de Cólquide, relacionado con la historia de Jasón y el Vellocino de Oro, Kutaisi es un destino cargado de historia, mitología y espiritualidad. La ciudad se extiende a orillas del río Rioni y combina su pasado glorioso con un ambiente tranquilo y acogedor. Entre sus mayores joyas están la Catedral de Bagrati y el Monasterio de Gelati, ambos declarados Patrimonio de la Humanidad por la UNESCO. Además, Kutaisi sirve como base ideal para explorar algunos de los paisajes naturales más espectaculares de Georgia, como la Cueva de Prometeo, con sus formaciones de estalactitas iluminadas, o el Cañón de Okatse, con su pasarela colgante sobre el abismo. Su gente es hospitalaria, su comida casera y deliciosa —con platos como el khachapuri o el khinkali—, y su vida urbana conserva una autenticidad que se ha perdido en muchos destinos europeos. Kutaisi es ideal para quienes buscan escapar de las rutas turísticas tradicionales y descubrir una ciudad que, aunque pequeña, rebosa cultura, historia y belleza natural.',
            'imagen' => 'kutaisi.jpg',
            ],
            [
            'titulo' => 'Torres del Paine, Chile',
            'descripcion' => 'Torres del Paine, en la Patagonia chilena, no es solo un destino de aventura: es un monumento natural al poder de la Tierra. Este parque nacional, considerado uno de los más espectaculares del planeta, ofrece un escenario que desafía la imaginación: picos graníticos que cortan el cielo, glaciares milenarios que crujen al romperse, lagos de un azul imposible y pampas abiertas donde corren libres guanacos, zorros y hasta pumas. Para los viajeros que buscan desconectarse del mundo moderno y reconectarse con lo esencial, este rincón del sur del mundo es una experiencia que transforma cuerpo y espíritu. La joya del parque son las tres torres que le dan nombre, gigantes de piedra que se elevan más de 2.800 metros sobre el nivel del mar. Llegar hasta su base requiere una caminata desafiante de varias horas, atravesando valles, bosques y zonas de alta montaña. Pero es solo el comienzo: el circuito W y el Circuito O son rutas de trekking de varios días que rodean todo el macizo del Paine, cruzando pasos remotos como el John Gardner, desde donde se contempla el impresionante glaciar Grey, un mar congelado de grietas azules hasta donde alcanza la vista. El idioma oficial es el español, pero el parque atrae a excursionistas de todo el mundo, por lo que es común encontrar una mezcla de culturas en los refugios y campamentos, donde se comparten comidas, historias y consejos bajo la luz de una linterna. El clima es impredecible: puedes experimentar las cuatro estaciones en un solo día, con vientos huracanados, lluvia horizontal y cielos despejados que permiten ver las estrellas con una claridad asombrosa. Además del trekking, Torres del Paine ofrece posibilidades para quienes desean hacer kayak entre icebergs, cabalgatas con gauchos patagónicos, fotografía de vida salvaje, y hasta navegar por el lago Grey en busca del frente del glaciar. Es un destino que exige preparación física y mental, pero que ofrece a cambio una de las formas más puras de aventura en el planeta. Este no es un viaje cómodo, ni predecible, ni fácil. Pero para quienes están dispuestos a aceptar el desafío, Torres del Paine no solo se deja ver, se deja sentir: en los músculos cansados, en el aire frío que entra en los pulmones, y en la emoción incontrolable al contemplar uno de los paisajes más sobrecogedores de la Tierra. Un destino para los verdaderos exploradores.',
            'imagen' => 'paine_chile.jpg',
            ],
            [
            'titulo' => 'Nepal',
            'descripcion' => 'Nepal es un país que invita a la introspección y al desafío personal. Ubicado entre las poderosas cumbres del Himalaya, es mucho más que el punto de partida hacia el Everest; es un lugar donde la espiritualidad, la naturaleza y la aventura conviven en un equilibrio único. Aquí se viene no solo a caminar, sino a transformarse. El Campo Base del Everest, el Annapurna Circuit o el Langtang Valley Trek no son simples rutas de senderismo, sino travesías físicas y mentales que atraviesan pueblos sherpas, monasterios budistas colgados de las montañas y valles donde el tiempo parece detenido. La altitud es un reto, pero también una oportunidad para encontrar fuerza interior y solidaridad con otros caminantes que comparten la misma ruta. El nepalí es el idioma oficial, pero en las distintas regiones se hablan muchas lenguas locales, y el tíbetano es común en zonas montañosas. La religiosidad impregna todo: ruedas de oración giran suavemente en los pueblos, y las banderas de oración ondean con el viento sobre los pasos de montaña como bendición para los viajeros. También hay espacio para otras aventuras: rafting en los ríos de deshielo, safaris en el Parque Nacional de Chitwan, parapente sobre el lago Phewa en Pokhara o incluso cursos de meditación vipassana en centros de retiro. Nepal es un país que enseña a caminar lento, a mirar hacia adentro, a respetar la montaña y a vivir con sencillez. No importa si llegas por una cima o por una búsqueda interior, lo seguro es que te irás con algo que no sabías que necesitabas encontrar.',
            'imagen' => 'nepal.jpg',
            ],
            [
            'titulo' => 'Laos',
            'descripcion' => 'Laos es uno de los secretos mejor guardados del sudeste asiático, un país sin mar pero con un río majestuoso —el Mekong— que lo atraviesa de norte a sur, marcando el ritmo de la vida y ofreciendo un sinfín de aventuras fluviales y culturales. Es el destino perfecto para quienes buscan autenticidad, tranquilidad y una belleza natural intacta, lejos del turismo masivo. A diferencia de sus vecinos más bulliciosos, Laos ofrece una experiencia serena pero profundamente enriquecedora. En Luang Prabang, una ciudad declarada Patrimonio de la Humanidad, las mañanas comienzan con el silencioso desfile de monjes budistas en busca de limosna, y terminan con puestas de sol doradas desde los templos que dominan la ciudad. Los aventureros pueden alquilar una moto y recorrer montañas selváticas, saltar en cascadas escondidas como Kuang Si Falls, practicar tubing o kayak en Vang Vieng, y explorar cuevas milenarias en Thakhek o Kong Lor. El idioma oficial es el lao, y aunque pocos locales hablan inglés en las zonas más remotas, la calidez y la hospitalidad de su gente trascienden cualquier barrera lingüística. Laos también es ideal para el viajero espiritual: puedes participar en ceremonias en templos budistas, aprender meditación o incluso vivir unos días como monje si estás dispuesto a seguir la disciplina del silencio. Viajar por Laos es abrazar lo simple, lo lento, lo profundo. Es un país donde la aventura no está en la velocidad, sino en la observación. Ideal para quienes buscan reconectar con la naturaleza y con su interior mientras navegan por ríos lentos, cruzan aldeas sobre pilotes o se dejan llevar por el ritmo pausado del sudeste asiático más auténtico.',
            'imagen' => 'laos.jpg',
            ],*/
        ]);
    }
}
